[package]
name = "ircv3_tags"
version = "0.1.0"
authors = ["m3id"]
edition = "2021"
description = "only IRCv3 tag part parse"
repository = "https://github.com/m3idnotfree/ircv3_tags"
license = "MIT OR Apache-2.0"
keywords = ["ircv3", "twitch", "tag"]


[dependencies]
nom = "7.1.3"

[dev-dependencies]
pretty_assertions = "1.4.0"
