[package]
name = "irc3_tags_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.48", features = ["full"] }

[lib]
proc_macro = true
